baseURL = "https://marianafnsc.github.io/osmiseraveis/"
languageCode = "pt-br"
title = "De lá pra cá"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "John Doe - None rights reserved"
enableEmoji = true
publishDir = "docs"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/2019_30.png"
  description ="relatos"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "mariana"
  thumbnail = "/images/2019_30.png"
  #description = "Creator of this blog."

[params.index]
  picture = "/images/2018_13.png"
  title = "mariana"
  subtitle = "algum lugar entre o bar e o lajedo"
  mdtext = '''
aqui eu falo sobre viagens legais e festivais de música
'''
  alertbar = false

[params.social]
  github = "<https://github.com/marianafnsc>"
  #linkedin = "<username>"
  #xing = "<username>"
  #medium = "<username>"
  twitter = "<https://twitter.com/fontesecas>"
  #instagram = "<username>"

## Main Menu
[[menu.main]]
    name = "ideias"
    weight = 100
    identifier = "ideias"
    url = "/ideias"
[[menu.main]]
    name = "sobre"
    identifier = "sobre"
    weight = 200
    url = "/"
#[[menu.main]]
    #name = "Imprint"
    #identifier = "imprint"
    #weight = 200
    #url = "/static/imprint"
